### ISSUE TITLE
rackt.org website repo

### ISSUE THREAD

**Issue by timdorr** [rackt/project-standards#1]
(Not sure where else to put this, but this seems like the best place for it)

Mind if I set up a `rackt.github.io` repo on the @rackt org? That can serve as the home for rackt.org. I wasn't sure the policy on creating new repos within the org. @knowbody and I are going to start on a documentation site initially focused on react-router. But it will eventually encompass all of the rackt projects and provide a jumping off point to find them (a la, twitter.github.io or microsoft.github.io)

cc: @mjackson

**Comment by mjackson** [comment]
Absolutely, that sounds like a great idea. All members of the rackt org
have the ability to create new repos.

I bought rackt.org the other day. I guess I'll need to point the DNS to GH
pages?

**Comment by timdorr** [comment]
Yeah, but this one has more side effects than others, so I figured I'd double-check :smile: 

For the DNS, you can either use an ALIAS or ANAME, if your provider supports it, pointed at `rackt.github.io`. If they don't, I'd recommend switching DNS over to Cloudflare, since it's free and they support ALIASes on apex domains.

**Comment by mjackson** [comment]
Thanks for double-checking :)

I'm using Cloudflare, per your suggestion. Seems like they do a lot of caching, so if stuff doesn't look right we may need to tweak it a bit. If there's a way you know of to grant access to the Cloudflare control panel to you, I'll gladly do it.

Thanks, @timdorr! Excited about this :)

**Comment by timdorr** [comment]
If you click the little cloud icon the right, you can set it to bypass their caching. We can turn that on later, as it will enable free SSL, which is neat.
